version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cardflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: finance_db
      MYSQL_USER: finance
      MYSQL_PASSWORD: finance123!
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--default-time-zone=+09:00"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpw"]
      interval: 10s
      timeout: 5s
      retries: 10