# 실행 방법 예시:
#   SPRING_PROFILES_ACTIVE=dev mvnw spring-boot:run
#   또는 IDE Run Configuration에서 active profile=dev

spring:
  application:
    name: cardflow-ai
  datasource:
    url: jdbc:mysql://localhost:3306/finance_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: finance
    password: finance123!
  sql:
    init:
      mode: always            # 존재하면 schema.sql 실행
      #encoding: UTF-8
      #schema-locations: file:./schema.sql  # 루트의 schema.sql 사용
  mvc:
    view:
      prefix: /WEB-INF/jsp/   # JSP 사용 시
      suffix: .jsp

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when_authorized

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.finance.domain
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: REUSE
    jdbc-type-for-null: NULL

logging:
  level:
    root: INFO
    org.apache.ibatis: DEBUG
